.TH "atomicx/atomicx.cpp" 3 "Sun Jan 30 2022" "AtomicX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atomicx/atomicx.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'atomicx\&.hpp'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBthread\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPOLY\fP   0x8408"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fByield\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define POLY   0x8408"

.SH "Function Documentation"
.PP 
.SS "void yield (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for AtomicX from the source code\&.
