.TH "main.cpp" 3 "Sun Jan 30 2022" "CorePartition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'atomicx\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBThreadConsummer\fP"
.br
.ti -1c
.RI "class \fBThread\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBListAllThreads\fP ()"
.br
.ti -1c
.RI "atomicx_time \fBAtomicx_GetTick\fP (void)"
.br
.ti -1c
.RI "void \fBAtomicx_SleepTick\fP (atomicx_time nSleep)"
.br
.ti -1c
.RI "atomicx::queue< size_t > \fBq\fP (5)"
.br
.ti -1c
.RI "atomicx::semaphore \fBsem\fP (2)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBnCounter\fP = 0"
.br
.ti -1c
.RI "size_t \fBnGlobalCount\fP = 0"
.br
.ti -1c
.RI "\fBThread\fP \fBt1\fP (500, 'Producer 1')"
.br
.ti -1c
.RI "\fBThreadConsummer\fP \fBe1\fP (500, 'Consumer 1')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "atomicx_time Atomicx_GetTick (void)"

.SS "void Atomicx_SleepTick (atomicx_time nSleep)"

.SS "void ListAllThreads ()"

.SS "int main ()"

.SS "atomicx::queue< size_t > q (5)"

.SS "atomicx::semaphore sem (2)"

.SH "Variable Documentation"
.PP 
.SS "\fBThreadConsummer\fP e1(500, 'Consumer 1') (500, 'Consumer 1')"

.SS "size_t nCounter = 0"

.SS "size_t nGlobalCount = 0"

.SS "\fBThread\fP t1(500, 'Producer 1') (500, 'Producer 1')"

.SH "Author"
.PP 
Generated automatically by Doxygen for CorePartition from the source code\&.
