.TH "thread::atomicx::Message" 3 "Sun Jan 30 2022" "AtomicX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread::atomicx::Message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <atomicx\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtag\fP"
.br
.ti -1c
.RI "size_t \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PROTECTED METHODS, THOSE WILL BE ONLY ACCESSIBLE BY THE THREAD ITSELF 
.SH "Field Documentation"
.PP 
.SS "size_t thread::atomicx::Message::message"

.SS "size_t thread::atomicx::Message::tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for AtomicX from the source code\&.
